default_stages: [pre-commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: cargo-fmt
        name: Format Rust codes
        language: system
        types: [rust]
        pass_filenames: false
        entry: cargo fmt

      - id: cargo-clippy
        name: Lint Rust codes
        language: system
        types: [rust]
        pass_filenames: false
        entry: cargo clippy

      - id: cargo-nextest
        name: Test Rust codes
        language: system
        types: [rust]
        pass_filenames: false
        entry: cargo nextest run
        args: [--workspace]
