{
 "title": "1Password Exporter",
 "description": "Grafana dashboard for 1Password Exporter (https://github.com/lasuillard/1password-exporter)",
 "tags": [
  "1password",
  "prometheus"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Resources",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "op_user_count_total", "legendFormat": "__auto" },
    { "expr": "op_group_count_total", "legendFormat": "__auto" },
    { "expr": "op_vault_count_total", "legendFormat": "__auto" },
    { "expr": "op_item_count_total", "legendFormat": "__auto" },
    { "expr": "op_document_count_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Current Account Info",
   "type": "table",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 18 },
   "targets": [
    { "expr": "op_account_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Quota Reset In (Account, R/W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_serviceaccount_ratelimit_reset_seconds{type=\"account\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Usage (Account, R/W)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 18 },
   "targets": [
    {
     "expr": "op_serviceaccount_ratelimit_used{type=\"account\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "op_serviceaccount_ratelimit_limit{type=\"account\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "op_serviceaccount_ratelimit_remaining{type=\"account\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Usage (Account, R/W)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_serviceaccount_ratelimit_used{type=\"account\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "op_serviceaccount_ratelimit_limit{type=\"account\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Users",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "targets": [
    { "expr": "op_user_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Groups",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "targets": [
    { "expr": "op_group_count_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Service Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Service Account Info",
   "type": "table",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 39 },
   "targets": [
    { "expr": "op_serviceaccount_whoami", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Quota Reset In (Token, Read)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_serviceaccount_ratelimit_reset_seconds{type=\"token\", action=\"read\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Usage (Token, Read)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 39 },
   "targets": [
    {
     "expr": "op_serviceaccount_ratelimit_used{type=\"token\", action=\"read\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "op_serviceaccount_ratelimit_limit{type=\"token\", action=\"read\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "op_serviceaccount_ratelimit_remaining{type=\"token\", action=\"read\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Usage (Token, Read)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_serviceaccount_ratelimit_used{type=\"token\", action=\"read\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "op_serviceaccount_ratelimit_limit{type=\"token\", action=\"read\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quota Reset In (Token, Write)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_serviceaccount_ratelimit_reset_seconds{type=\"token\", action=\"write\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Usage (Token, Write)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 49 },
   "targets": [
    {
     "expr": "op_serviceaccount_ratelimit_used{type=\"token\", action=\"write\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "op_serviceaccount_ratelimit_limit{type=\"token\", action=\"write\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "op_serviceaccount_ratelimit_remaining{type=\"token\", action=\"write\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Usage (Token, Write)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_serviceaccount_ratelimit_used{type=\"token\", action=\"write\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "op_serviceaccount_ratelimit_limit{type=\"token\", action=\"write\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Vault", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Number of Vaults",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 60 },
   "targets": [
    { "expr": "op_vault_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Items per Vault",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 60 },
   "targets": [
    { "expr": "op_item_count_per_vault", "legendFormat": "{{vault}}" }
   ]
  },
  {
   "title": "Documents per Vault",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 60 },
   "targets": [
    { "expr": "op_document_count_per_vault", "legendFormat": "{{vault}}" },
    {
     "expr": "op_document_file_size_per_vault_bytes",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  { "title": "Item", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Number of Items",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 71 },
   "targets": [
    { "expr": "op_item_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Items per Category",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 71 },
   "targets": [
    { "expr": "op_item_count_per_category", "legendFormat": "{{category}}" }
   ]
  },
  {
   "title": "Items per Tag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 71 },
   "targets": [
    { "expr": "op_item_count_per_tag", "legendFormat": "{{tag}}" }
   ]
  },
  { "title": "Document", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Number of Documents",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 82 },
   "targets": [
    { "expr": "op_document_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Documents per Tag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 82 },
   "targets": [
    { "expr": "op_document_count_per_tag", "legendFormat": "{{tag}}" },
    {
     "expr": "op_document_file_size_per_tag_bytes",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Exporter Build Info",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 93 },
   "targets": [
    { "expr": "op_exporter_buildinfo", "legendFormat": "__auto" }
   ]
  }
 ]
}